import { FC, ReactNode } from 'react';
import '@/app/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface HighProteinLayout {
  children: ReactNode;
}

const HighProteinLayout: FC<HighProteinLayout> = ({ children }) => {
  return (
    <div className="overflow-hidden bg-color-six">
      <div className="mx-auto my-3 h-max">{children}</div>
    </div>
  );
};

export default HighProteinLayout;
