import { FC, ReactNode } from 'react';
import '@/app/globals.css';
import { NavigationBottom } from '@/components';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface HomeLayoutProps {
  children: ReactNode;
}

const HomeLayout: FC<HomeLayoutProps> = ({ children }) => {
  return (
    <>
      <header>head er</header>
      <section>{children}</section>
      <div className="absolute bottom-0 w-full  pt-2 shadow-[0px_-5px_5px_-5px_rgb(0,0,0,0.3)]">
        <NavigationBottom />
      </div>
    </>
  );
};

export default HomeLayout;
